### ISSUE TITLE
Clasp not installed [ERR_PACKAGE_PATH_NOT_EXPORTED]

### ISSUE THREAD

**Issue by xAt0mZ** [ijusplab/vue-cli-plugin-gas#9]
Kind of following #5, trying to use this plugin I'm facing the following error : `ERR_PACKAGE_PATH_NOT_EXPORTED`

<details>
<summary>Trace</summary>

```
Running completion hooks...Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './package.json' is not defined by "exports" in /home/baron_l/projects/perso/dfg/dfg-tierlist-gs-vue/node_modules/@google/clasp/package.json
    at new NodeError (node:internal/errors:370:5)
    at throwExportsNotFound (node:internal/modules/esm/resolve:335:9)
    at packageExportsResolve (node:internal/modules/esm/resolve:560:3)
    at resolveExports (node:internal/modules/cjs/loader:476:36)
    at Function.Module._findPath (node:internal/modules/cjs/loader:516:31)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:913:27)
    at Function.resolve (node:internal/modules/cjs/helpers:99:19)
    at isInstalled (/home/baron_l/projects/perso/dfg/dfg-tierlist-gs-vue/node_modules/@ijusplab/vue-cli-plugin-gas/utils/claspHelpers.js:53:33)
    at checkVersion (/home/baron_l/projects/perso/dfg/dfg-tierlist-gs-vue/node_modules/@ijusplab/vue-cli-plugin-gas/utils/claspHelpers.js:117:17)
    at setup (/home/baron_l/projects/perso/dfg/dfg-tierlist-gs-vue/node_modules/@ijusplab/vue-cli-plugin-gas/utils/claspHelpers.js:166:3) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}
⚓  Running completion hooks...
 ERROR  Error: Clasp not installed
Error: Clasp not installed
    at checkVersion (/home/baron_l/projects/perso/dfg/dfg-tierlist-gs-vue/node_modules/@ijusplab/vue-cli-plugin-gas/utils/claspHelpers.js:118:23)
    at setup (/home/baron_l/projects/perso/dfg/dfg-tierlist-gs-vue/node_modules/@ijusplab/vue-cli-plugin-gas/utils/claspHelpers.js:166:3)
    at Installer.setup (/home/baron_l/projects/perso/dfg/dfg-tierlist-gs-vue/node_modules/@ijusplab/vue-cli-plugin-gas/utils/claspHelpers.js:179:24)
    at /home/baron_l/projects/perso/dfg/dfg-tierlist-gs-vue/node_modules/@ijusplab/vue-cli-plugin-gas/generator/index.js:49:27
    at runGenerator (/home/baron_l/.config/yarn/global/node_modules/@vue/cli/lib/invoke.js:132:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async invoke (/home/baron_l/.config/yarn/global/node_modules/@vue/cli/lib/invoke.js:92:3)
```

</details>

<details>
<summary>Environment</summary>

```
> vue info

System:
    OS: Linux 5.12 Arch Linux
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
  Binaries:
    Node: 16.5.0 - /usr/bin/node
    Yarn: Not Found
    npm: 7.17.0 - /usr/bin/npm
  Browsers:
    Chrome: Not Found
    Firefox: 90.0
  npmPackages:
    @ijusplab/vue-cli-plugin-gas: ~2.0.6 => 2.0.6 
    @vue/babel-helper-vue-jsx-merge-props:  1.2.1 
    @vue/babel-helper-vue-transform-on:  1.0.2 
    @vue/babel-plugin-jsx:  1.0.6 
    @vue/babel-plugin-transform-vue-jsx:  1.2.1 
    @vue/babel-preset-app:  4.5.13 
    @vue/babel-preset-jsx:  1.2.4 
    @vue/babel-sugar-composition-api-inject-h:  1.2.1 
    @vue/babel-sugar-composition-api-render-instance:  1.2.4 
    @vue/babel-sugar-functional-vue:  1.2.2 
    @vue/babel-sugar-inject-h:  1.2.2 
    @vue/babel-sugar-v-model:  1.2.3 
    @vue/babel-sugar-v-on:  1.2.3 
    @vue/cli-overlay:  4.5.13 
    @vue/cli-plugin-babel: ~4.5.0 => 4.5.13 
    @vue/cli-plugin-eslint: ~4.5.0 => 4.5.13 
    @vue/cli-plugin-router: ~4.5.0 => 4.5.13 
    @vue/cli-plugin-vuex: ~4.5.0 => 4.5.13 
    @vue/cli-service: ~4.5.0 => 4.5.13 
    @vue/cli-shared-utils:  4.5.13 
    @vue/compiler-core:  3.2.2 
    @vue/compiler-dom:  3.2.2 
    @vue/compiler-sfc: ^3.0.0 => 3.2.2 
    @vue/compiler-ssr:  3.2.2 
    @vue/component-compiler-utils:  3.2.2 
    @vue/devtools-api:  6.0.0-beta.15 
    @vue/eslint-config-prettier: ^6.0.0 => 6.0.0 
    @vue/preload-webpack-plugin:  1.1.2 
    @vue/reactivity:  3.2.2 
    @vue/runtime-core:  3.2.2 
    @vue/runtime-dom:  3.2.2 
    @vue/shared:  3.2.2 
    @vue/web-component-wrapper:  1.3.0 
    eslint-plugin-vue: ^7.0.0 => 7.16.0 
    typescript:  4.3.5 
    vue: ^3.0.0 => 3.2.2 
    vue-eslint-parser:  7.10.0 
    vue-hot-reload-api:  2.3.4 
    vue-loader:  15.9.8 (16.5.0)
    vue-router: ^4.0.0-0 => 4.0.11 
    vue-style-loader:  4.1.3 
    vue-svg-inline-loader: ^1.4.6 => 1.5.1 
    vue-template-es2015-compiler:  1.9.1 
    vuex: ^4.0.0-0 => 4.0.2 
  npmGlobalPackages:
    @vue/cli: 4.5.13
```
</details>

Tested scenarios:
* Having only clasp installed globally results in #5 error
* Using `NODE_PATH=/home/[...]/.config/yarn/global/node_modules vue add @ijusplab/vue-cli-plugin-gas` results in the above error. Same with npm global path ad `NODE_PATH`
* Adding clasp as a dev dependency results in the above error

Any idea on how to fix this?

**Comment by murashi-sn** [comment]
@xAt0mZ 
If possible, could you please check if the same error occurs in the latest version?
The required version of the tool to be used is specified in the README.
